version: '2'
services:
  web:
    restart: always
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    # expose:
    #   - "8001"
    # links:
#       - postgres:postgres
#       - redis:redis
    depends_on:
      - postgres
      - redis
    command: python manage.py runserver 0.0.0.0:8000

  # nginx:
#     restart: never
#     build: ./nginx/
#     ports:
#       - "80:80"
#     volumes:
#       - /www/static
#     volumes_from:
#       - web
#     links:
#       - web:web

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"

  # data:
#     restart: always
#     image: postgres:latest
#     volumes:
#       - /var/lib/postgresql
#     command: "true"

  # mongodata:
  #   image: mongo:3.0.4
  #   volumes:
  #     - /data/db
  #   command: --break-mongo
  # mongo:
  #   image: mongo:3.0.4
  #   volumes_from:
  #     - mongodata
  #   ports:
  #     - "27017:27017"
  #   command: --smallfiles --rest --auth
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"