version: '2'
services:
#  web:
#    restart: always
#    build: ./web
#    volumes:
#      - .:/usr/src/app
#    ports:
#      - "8001:8001"
#    # links:
##       - postgres:postgres
##       - redis:redis
#    depends_on:
#      - postgres
#      - redis
#    command: python manage.py runserver 0.0.0.0:8001

  # nginx:
#     restart: never
#     build: ./nginx/
#     ports:
#       - "80:80"
#     volumes:
#       - /www/static
#     volumes_from:
#       - web
#     links:
#       - web:web

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
