version: '2'
services:
  web:
    restart: never
    build: ./web
    volumes:
      - /usr/src/app/static
    expose:
      - "8001"
    links:
      - postgres:postgres
      - redis:redis
    command: /usr/local/bin/gunicorn resify.wsgi:application -w 2 -b 0.0.0.0:8000

  nginx:
    restart: never
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - web:web

  postgres:
    restart: never
    image: postgres:latest
    volumes_from:
      - data
    ports:
      - "5432:5432"

  data:
    restart: never
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: "true"

  # mongodata:
  #   image: mongo:3.0.4
  #   volumes:
  #     - /data/db
  #   command: --break-mongo
  # mongo:
  #   image: mongo:3.0.4
  #   volumes_from:
  #     - mongodata
  #   ports:
  #     - "27017:27017"
  #   command: --smallfiles --rest --auth
  redis:
    restart: never
    image: redis:latest
    ports:
      - "6379:6379"