# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-23 16:10
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='New Resume', max_length=128, verbose_name='Resume name')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='Resume summary')),
                ('work', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('education', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('awards', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('skills', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('references', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='date deleted')),
            ],
            options={
                'verbose_name': 'resume',
                'verbose_name_plural': 'resumes',
            },
        ),
        migrations.CreateModel(
            name='ResumeTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('summary', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'theme',
                'verbose_name_plural': 'themes',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('start_page', models.SmallIntegerField(choices=[(1, 'Resume'), (2, 'Jobs'), (3, 'Business')], default=1)),
                ('availability', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('social_profiles', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('location', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('active_resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userdetails.Resume')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user detail',
                'verbose_name_plural': 'user details',
            },
        ),
        migrations.AddField(
            model_name='resumetheme',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userdetails.UserDetails'),
        ),
        migrations.AddField(
            model_name='resume',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='resumes', to='userdetails.UserDetails'),
        ),
        migrations.AddField(
            model_name='resume',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userdetails.ResumeTheme'),
        ),
    ]
