# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-23 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
