# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-10-02 18:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0003_auto_20160723_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='awards',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='references',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='work',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[]),
        ),
    ]
