# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-08-19 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0003_auto_20160723_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
