# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-08-24 00:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0005_auto_20160819_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='availability',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{"days": {"Sat": false, "Sun": false, "Thurs": true, "Tues": true, "Wed": true, "Fri": true, "Mon": true}, "phone": "", "time": {"start": null, "end": null}}', null=True),
        ),
    ]
